import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import fs from 'node:fs'
import test from 'node:test'

const read = (path) => fs.readFileSync(new URL(path, import.meta.url), 'utf8')
const SERVICE_SOURCE = read('../Sources/Service/DshService.swift')
const ACCESS_SOURCE = read('../Sources/Service/DshAccessController.swift')
const PROTOCOL_SOURCE = read('../Sources/Service/DshControlProtocol.swift')
const PROCESS_IO_SOURCE = read('../Sources/Service/DshProcessIO.swift')
const HEALTH_SOURCE = read('../Sources/Service/DshRuntimeHealthClient.swift')
const COOKIE_SOURCE = read('../Sources/MainWindow/DshRendererCookieStore.swift')
const UPSTREAM_COOKIE_SOURCE = read('../Sources/MainWindow/DshUpstreamCookieStore.swift')
const WINDOW_SOURCE = read('../Sources/MainWindow/MainWindowController.swift')
const WEB_SHELL_SOURCE = read('../Sources/MainWindow/DshWebShell.swift')
const STATE_SOURCE = read('../Sources/State/DshState.swift')
const SETTINGS_SOURCE = read('../Sources/SettingsUI/SettingsViewModel.swift')
const APP_SOURCE = read('../Sources/AppDelegate.swift')
const PLUGIN_SOURCE = read('../Sources/Plugins/DshPluginManager.swift')
const PROJECT_SOURCE = read('../DSH.xcodeproj/project.pbxproj')
const HOST_PACKAGE = read('../assets/dsh-desktop-host/package.json')
const HOST_PATCH = read('../assets/dsh-desktop-host/cordis.patch.yml')
const HOST_WEB_SERVER = read('../assets/dsh-desktop-host/webserver.js')
const HOST_CONTROL = read('../assets/dsh-desktop-host/control.js')
const HOST_ROUTE = read('../assets/dsh-desktop-host/browser-url-route.js')
const HOST_ACCESS = read('../assets/dsh-desktop-host/access-state.js')
const HOST_BROKER = read('../assets/dsh-desktop-host/upstream-session-broker.js')
const LAN_ROUTE = read('../assets/dsh-desktop-host/lan-url-route.js')
const LAN_INGRESS = read('../assets/dsh-desktop-host/lan-http-ingress.js')
const BOOTSTRAP_SOURCE = read('../assets/dsh-runtime-bootstrap.mjs')
const NODE_RUNTIME_SOURCE = read('../Sources/Service/NodeRuntime.swift')

test('managed DSH receives access only through an inherited control pipe', () => {
  assert.match(SERVICE_SOURCE, /standardInput\s*=\s*access\.controlReadHandle/)
  assert.match(SERVICE_SOURCE, /DSH_DESKTOP_LAUNCH"\]\s*=\s*"1"/)
  assert.match(SERVICE_SOURCE, /DSH_DESKTOP_PORT"\]\s*=\s*String\(actualPort\)/)
  assert.match(SERVICE_SOURCE, /try\s+access\.sendBootstrap\([\s\S]*profile: state\.appProfile[\s\S]*port: actualPort/)
  assert.match(SERVICE_SOURCE, /buildArguments\(runtimeBootstrap: runtimeBootstrap\)/)
  assert.match(SERVICE_SOURCE, /try\s+await\s+processIO\.waitForReady\(\)/)
  assert.match(SERVICE_SOURCE, /controlWriteHandle\.closeFile\(\)/)
  assert.doesNotMatch(SERVICE_SOURCE, /rendererToken.*environment|environment.*rendererToken/)
  assert.doesNotMatch(SERVICE_SOURCE, /rendererToken.*argument|argument.*rendererToken/)
})

test('generation credentials and NDJSON protocol are validated before encoding', () => {
  assert.match(ACCESS_SOURCE, /SecRandomCopyBytes/)
  assert.match(ACCESS_SOURCE, /replacingOccurrences\(of: "\+", with: "-"\)/)
  assert.match(ACCESS_SOURCE, /replacingOccurrences\(of: "\/", with: "_"\)/)
  assert.match(PROTOCOL_SOURCE, /maxLineBytes\s*=\s*16\s*\*\s*1024/)
  assert.match(PROTOCOL_SOURCE, /outputFormatting\s*=\s*\[\.sortedKeys\]/)
  assert.match(PROTOCOL_SOURCE, /DshAppProfile\(rawValue: message\.profile\)/)
  assert.match(ACCESS_SOURCE, /profile\.rawValue/)
  assert.match(PROTOCOL_SOURCE, /Data\(\[0x0A\]\)/)
  assert.match(HOST_CONTROL, /MAX_LINE_BYTES\s*=\s*16\s*\*\s*1024/)
  assert.match(HOST_CONTROL, /JSON\.parse/)
  assert.match(HOST_CONTROL, /process\.exit\(1\)/)
  assert.match(HOST_CONTROL, /accessState\.applyPolicy/)
  assert.match(HOST_CONTROL, /shutdownControlledAccess/)
  assert.match(HOST_CONTROL, /control stream closed/)
  assert.match(HOST_CONTROL, /validateBootstrap/)
  assert.match(HOST_CONTROL, /waitForDesktopBootstrap/)
  assert.match(BOOTSTRAP_SOURCE, /process\.title = "DSH Web Runtime"/)
  assert.match(BOOTSTRAP_SOURCE, /await import\(bootstrap\.entryPath\)/)
  assert.match(STATE_SOURCE, /browserAccessEnabled/)
  assert.match(STATE_SOURCE, /networkExposure/)
  assert.match(STATE_SOURCE, /decodeIfPresent\(Bool\.self, forKey: \.browserAccessEnabled\) \?\? false/)
})

test('a managed control-pipe EOF exits before generation instead of leaving Node alive', async () => {
  const controlModule = new URL('../assets/dsh-desktop-host/control.js', import.meta.url).href
  const script = `import { startDesktopControl } from ${JSON.stringify(controlModule)}; startDesktopControl();`
  const child = spawn(process.execPath, ['--input-type=module', '--eval', script], {
    env: { ...process.env, DSH_DESKTOP_LAUNCH: '1' },
    stdio: ['pipe', 'ignore', 'pipe'],
  })
  let stderr = ''
  child.stderr.setEncoding('utf8')
  child.stderr.on('data', (chunk) => { stderr += chunk })
  child.stdin.end()

  const result = await new Promise((resolve, reject) => {
    child.once('error', reject)
    child.once('exit', (code, signal) => resolve({ code, signal }))
  })
  assert.equal(result.code, 1)
  assert.equal(result.signal, null)
  assert.match(stderr, /control stream closed before generation/)
})

test('browser access updates the live policy and opens only a short-lived Host URL', () => {
  assert.match(SETTINGS_SOURCE, /setBrowserAccessEnabled\(_ enabled: Bool\)/)
  assert.match(SETTINGS_SOURCE, /DshService\.shared\.setBrowserAccessEnabled/)
  assert.match(SETTINGS_SOURCE, /NSWorkspace\.shared\.open\(url\)/)
  assert.match(HEALTH_SOURCE, /URLSessionConfiguration\.ephemeral/)
  assert.match(WINDOW_SOURCE, /dsh_swift_renderer=\\\(session\.access\.rendererToken\)/)
  assert.match(WINDOW_SOURCE, /fetchAuthenticatedBrowserURL/)
  assert.match(WINDOW_SOURCE, /isCurrentRuntimeWebURL/)
  assert.match(WINDOW_SOURCE, /isBrowserHandoffURL/)
  assert.match(WINDOW_SOURCE, /dsh-browser-ticket/)
  assert.match(WINDOW_SOURCE, /different port are different authorities/)
  assert.match(HOST_ROUTE, /__dsh_swift\/browser-url/)
  assert.match(HOST_ROUTE, /__dsh_swift\/browser-handoff/)
  assert.match(HOST_ROUTE, /CLASSIFICATIONS\.renderer/)
  assert.match(HOST_ROUTE, /connection\.authenticatedUrl/)
  assert.match(HOST_ACCESS, /dsh-browser-ticket/)
  assert.match(HOST_ROUTE, /cache-control.*no-store/i)
})

test('LAN access uses a separate authenticated HTTP ingress while the DSH server stays loopback-only', () => {
  assert.match(SERVICE_SOURCE, /setNetworkExposure\(_ exposure: DshNetworkExposure\)/)
  assert.match(SERVICE_SOURCE, /networkExposure: state\.networkExposure/)
  assert.match(PROCESS_IO_SOURCE, /loopback\|lan/)
  assert.match(WINDOW_SOURCE, /fetchLANURL/)
  assert.match(SETTINGS_SOURCE, /setNetworkExposure\(_ enabled: Bool\)/)
  assert.match(SETTINGS_SOURCE, /copyLANURL/)
  assert.match(LAN_ROUTE, /__dsh_swift\/lan-url/)
  assert.match(LAN_ROUTE, /CLASSIFICATIONS\.renderer/)
  assert.match(LAN_ROUTE, /networkExposure !== NETWORK_EXPOSURES\.lan/)
  assert.match(LAN_INGRESS, /listenHost = "0\.0\.0\.0"/)
  assert.match(LAN_INGRESS, /hasValidLanCredential/)
  assert.match(LAN_INGRESS, /RENDERER_COOKIE_NAME/)
  assert.match(LAN_INGRESS, /backendHeaders/)
  assert.match(LAN_INGRESS, /createUpstreamSessionBroker/)
  assert.match(LAN_INGRESS, /const releaseClientSocket = broker\.trackSocket\(request\.socket, credential\.browserToken\)/)
  assert.match(LAN_INGRESS, /response\.once\("finish", releaseClientSocket\)/)
  assert.match(LAN_INGRESS, /proxyResponse\.once\("end", releaseBackendSocket\)/)
  assert.match(LAN_INGRESS, /releaseBackendSocket = broker\.trackSocket\(socket, credential\.browserToken\)/)
  assert.match(LAN_INGRESS, /dsh-auth-/)
  assert.match(HOST_BROKER, /cookiesFor/)
  assert.match(HOST_BROKER, /exchangeOverLoopback/)
  assert.match(WINDOW_SOURCE, /LAN 实际入口/)
  assert.match(HOST_WEB_SERVER, /createLanHTTPIngress/)
  assert.match(HOST_PACKAGE, /lan-url-route/)
  assert.match(HOST_PACKAGE, /lan-http-ingress/)
  assert.match(HOST_PACKAGE, /upstream-session-broker/)
})

test('readiness requires both the loopback URL and the matching control generation', () => {
  assert.match(PROCESS_IO_SOURCE, /controlReadyGeneration\s*==\s*expectedGeneration/)
  assert.match(PROCESS_IO_SOURCE, /dsh desktop control ready/)
  assert.match(PROCESS_IO_SOURCE, /readabilityHandler/)
  assert.match(PROCESS_IO_SOURCE, /maxLogBytes\s*=\s*256\s*\*\s*1024/)
  assert.match(PROCESS_IO_SOURCE, /redact/)
  assert.match(PROCESS_IO_SOURCE, /DshProcessIOError\.generationMismatch/)
})

test('WebKit receives a strict, HttpOnly, session-only host cookie for each generation', () => {
  assert.match(COOKIE_SOURCE, /dsh_swift_renderer/)
  assert.match(COOKIE_SOURCE, /isHTTPOnly/)
  assert.match(COOKIE_SOURCE, /sameSiteStrict/)
  assert.match(COOKIE_SOURCE, /discard/)
  assert.match(COOKIE_SOURCE, /for cookie in oldCookies where/)
  assert.match(WINDOW_SOURCE, /bootstrapWebProfileManifestIfMissing\(\)/)
  assert.match(WINDOW_SOURCE, /ensureDesktopHostPlugin\(\)/)
  assert.match(WINDOW_SOURCE, /try\s+await\s+rendererCookieStore\.install\(for: session\)/)
  assert.match(WINDOW_SOURCE, /let firstNavigationURL = session\.endpoint\.bootstrapURL \?\? session\.originURL/)
  assert.match(WINDOW_SOURCE, /webView\?\.\s*load\(URLRequest\(url: firstNavigationURL\)\)/)
  assert.match(UPSTREAM_COOKIE_SOURCE, /dsh-auth-/)
  assert.match(UPSTREAM_COOKIE_SOURCE, /prepareForNewSession/)
  assert.match(UPSTREAM_COOKIE_SOURCE, /waitForAuthenticatedCookies/)
  assert.match(UPSTREAM_COOKIE_SOURCE, /sameSiteStrict/)
  assert.match(UPSTREAM_COOKIE_SOURCE, /SHA256\.hash/)
  assert.match(WINDOW_SOURCE, /session\.endpoint\.withoutBootstrap\(\)/)
  assert.match(WINDOW_SOURCE, /healthCredentials\(/)
})

test('native health probes use isolated explicit credentials and bounded same-origin redirects', () => {
  assert.match(HEALTH_SOURCE, /httpShouldSetCookies\s*=\s*false/)
  assert.match(HEALTH_SOURCE, /httpCookieStorage\s*=\s*nil/)
  assert.match(HEALTH_SOURCE, /willPerformHTTPRedirection/)
  assert.match(HEALTH_SOURCE, /maxRedirects/)
  assert.match(HEALTH_SOURCE, /redirectOrigin == origin/)
  assert.match(HEALTH_SOURCE, /setCookieHeaders/)
  assert.match(WINDOW_SOURCE, /DshRuntimeHealthClient\.isHTMLPage/)
  assert.match(WINDOW_SOURCE, /credentials:\s*\.anonymous/)
})

test('alpha Runtime health verifies the real WebKit Remote stream and can renew auth once', () => {
  assert.match(WEB_SHELL_SOURCE, /webUIConnectionProbeScript/)
  assert.match(WEB_SHELL_SOURCE, /new URL\('\/api\/remote\.mux'/)
  assert.match(WEB_SHELL_SOURCE, /new WebSocket\(target\.toString\(\)\)/)
  assert.match(WINDOW_SOURCE, /callAsyncJavaScript\(/)
  assert.match(WINDOW_SOURCE, /verifyWebKitConnection\(session: session\)/)
  assert.match(WINDOW_SOURCE, /authenticatedCookies\(for: session\)/)
  assert.match(WINDOW_SOURCE, /maxAutomaticAuthenticationRecoveries = 1/)
  assert.match(WINDOW_SOURCE, /restartDshService\(\)/)
  assert.match(WINDOW_SOURCE, /try await self\.withRuntimeOperation/)
  assert.match(WINDOW_SOURCE, /restartDshServiceDuringOperation\(\)/)
  assert.match(WINDOW_SOURCE, /authenticationRequired/)
  assert.match(WINDOW_SOURCE, /self\.reloadDsh\(\)/)
  assert.match(UPSTREAM_COOKIE_SOURCE, /public func authenticatedCookies\(for session: DshServiceSession\)/)
})

test('first launch bootstraps the canonical profile and installs the host before DSH starts', () => {
  assert.match(PLUGIN_SOURCE, /bootstrapWebProfileManifestIfMissing/)
  assert.match(PLUGIN_SOURCE, /ensureManagedProfileWorkspaceConfiguration/)
  assert.match(PLUGIN_SOURCE, /pnpm-workspace\.yaml/)
  assert.match(PLUGIN_SOURCE, /packages:\\n  - \./)
  assert.match(PLUGIN_SOURCE, /nodeLinker: hoisted/)
  assert.match(PLUGIN_SOURCE, /autoInstallPeers: false/)
  assert.match(PLUGIN_SOURCE, /Preserve custom settings such as allowBuilds/)
  assert.match(PLUGIN_SOURCE, /"name": "dsh-profile-/)
  assert.match(PLUGIN_SOURCE, /profileDirectory\(for profile: DshAppProfile\)/)
  assert.match(PLUGIN_SOURCE, /activeProfileDirectory/)
  assert.match(PLUGIN_SOURCE, /dsh\.profile\.bundles/)
  assert.match(PLUGIN_SOURCE, /proc\.arguments = \[[\s\S]*"add"[\s\S]*file:/)
  assert.match(PLUGIN_SOURCE, /@deepseek-ai\/dsh-host-webserver@/)
  assert.match(PLUGIN_SOURCE, /validateDesktopHostBundle/)
  assert.match(PLUGIN_SOURCE, /isInstalledDesktopHostBundle/)
  assert.match(PLUGIN_SOURCE, /CryptoKit/)
  assert.match(PLUGIN_SOURCE, /SHA256/)
  assert.match(PLUGIN_SOURCE, /desktopHostBundleFingerprint/)
  assert.match(PLUGIN_SOURCE, /--force/)
  assert.match(PLUGIN_SOURCE, /removeInstalledDesktopHostBundle/)
  assert.match(PLUGIN_SOURCE, /isInstalledWebServerPackage/)
  assert.match(PLUGIN_SOURCE, /repairProfileDependenciesIfNeeded\(registry: String\? = nil\) async throws -> Bool/)
  assert.match(PLUGIN_SOURCE, /\"install\",[\s\S]*\"--config\.minimum-release-age=0\"/)
  assert.match(PLUGIN_SOURCE, /\"install\",[\s\S]*\"--frozen-lockfile\"/)
  assert.match(PLUGIN_SOURCE, /profileDependenciesNeedInstall/)
  assert.match(WINDOW_SOURCE, /ensureDesktopHostPlugin\(\)[\s\S]*repairProfileDependenciesIfNeeded\(\)/)
  assert.match(PLUGIN_SOURCE, /DshProcessOutputCollector/)
  assert.match(PLUGIN_SOURCE, /runProcess\(proc, stdout: stdout, stderr: stderr\)/)
  assert.match(PLUGIN_SOURCE, /supply-chain verification/)
  assert.match(WINDOW_SOURCE, /SettingsViewModel\.shared\.refreshPlugins\(\)/)
  assert.match(APP_SOURCE, /let restartItem = appMenu\.addItem\([\s\S]*#selector\(restartService\)/)
  assert.match(APP_SOURCE, /restartItem\.target = self/)
})

test('profile repair is scoped, lazy, and provides a manual recovery command', () => {
  assert.match(PLUGIN_SOURCE, /healthy profiles are not reinstalled/)
  assert.match(PLUGIN_SOURCE, /global pnpm configuration is never changed/)
  assert.match(PLUGIN_SOURCE, /dsh plugin --profile desktop install --config\.minimum-release-age=0/)
  assert.match(PLUGIN_SOURCE, /node_modules[\s\S]*\.modules\.yaml/)
  assert.match(PLUGIN_SOURCE, /packageManifestURL\(name: String, profileDir: URL\)/)
})

test('the managed host webserver dependency is hidden from user plugin management', () => {
  assert.match(PLUGIN_SOURCE, /internalPluginDependencyNames[\s\S]*@deepseek-ai\/dsh-host-webserver/)
  assert.match(PLUGIN_SOURCE, /guard !Self\.internalPluginDependencyNames\.contains\(name\) else \{ continue \}/)
  assert.match(PLUGIN_SOURCE, /guard !Self\.internalPluginDependencyNames\.contains\(pkgName\) else \{ continue \}/)
  assert.match(PLUGIN_SOURCE, /不能直接安装 DSH 内部依赖/)
  assert.match(PLUGIN_SOURCE, /不能直接更新 DSH 内部依赖/)
  assert.match(PLUGIN_SOURCE, /不能直接卸载 DSH 内部依赖/)
  assert.match(PLUGIN_SOURCE, /filter \{ !\$0\.isManaged && !\$0\.isLocal \}/)
  assert.match(PLUGIN_SOURCE, /var arguments = \["update"\] \+ pluginNames \+ \["--latest"\][\s\S]*proc\.arguments = arguments \+ registryArguments\(\)/)
})

test('plugin removal uses pnpm-supported arguments and preserves diagnostics', () => {
  const removeBlock = PLUGIN_SOURCE.match(
    /public func removePlugin\(name: String\) async throws \{[\s\S]*?\n    \}\n\n    private func updateProfileBundle/
  )?.[0]
  assert.ok(removeBlock)
  assert.match(removeBlock, /proc\.arguments = \["remove", name, "--config\.minimum-release-age=0", "--reporter=append-only"\]/)
  assert.doesNotMatch(removeBlock, /registryArguments\(\)/)
  assert.match(removeBlock, /env\["npm_config_registry"\]/)
  assert.match(removeBlock, /let stdout = Pipe\(\)/)
  assert.match(removeBlock, /let stderr = Pipe\(\)/)
  assert.match(removeBlock, /processOutput\(result\)/)
  assert.match(removeBlock, /退出码 .*result\.status/)
})

test('the upstream webserver is replaced and all request boundaries share the fence', () => {
  assert.match(HOST_PATCH, /id: webserver[\s\S]*disabled: true/)
  assert.match(HOST_PATCH, /name: dsh-desktop-host\/webserver/)
  assert.match(HOST_PATCH, /host: 127\.0\.0\.1/)
  assert.match(HOST_WEB_SERVER, /register\(route\)/)
  assert.match(HOST_WEB_SERVER, /registerFallback\(handler\)/)
  assert.match(HOST_WEB_SERVER, /registerUpgrade\(route\)/)
  assert.match(HOST_WEB_SERVER, /REQUIRED_UPSTREAM_METHODS/)
  assert.match(HOST_WEB_SERVER, /incompatible with the installed DSH runtime/)
  assert.match(HOST_WEB_SERVER, /requestPassesLoopbackFence/)
  assert.match(HOST_WEB_SERVER, /rejectUpgrade/)
  assert.match(HOST_WEB_SERVER, /accessState\.trackOrdinarySocket/)
  assert.match(HOST_WEB_SERVER, /createBrowserURLRoute/)
  assert.match(HOST_WEB_SERVER, /createBrowserHandoffRoute/)
  assert.match(HOST_ROUTE, /referrer-policy/i)
  assert.match(HOST_PACKAGE, /browser-url-route/)
  assert.match(HOST_PACKAGE, /"\.\/webserver": "\.\/webserver\.js"/)
  assert.match(HOST_PACKAGE, /"@deepseek-ai\/dsh-host-webserver"/)
  assert.match(PROJECT_SOURCE, /Security\.framework/)
  assert.match(PROJECT_SOURCE, /dsh-runtime-bootstrap\.mjs/)
  assert.match(NODE_RUNTIME_SOURCE, /resolveRuntimeBootstrap/)
})
