import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import fs from 'node:fs'
import test from 'node:test'

const read = (path) => fs.readFileSync(new URL(path, import.meta.url), 'utf8')
const SERVICE_SOURCE = read('../Sources/Service/DshService.swift')
const ACCESS_SOURCE = read('../Sources/Service/DshAccessController.swift')
const PROTOCOL_SOURCE = read('../Sources/Service/DshControlProtocol.swift')
const PROCESS_IO_SOURCE = read('../Sources/Service/DshProcessIO.swift')
const COOKIE_SOURCE = read('../Sources/MainWindow/DshRendererCookieStore.swift')
const WINDOW_SOURCE = read('../Sources/MainWindow/MainWindowController.swift')
const STATE_SOURCE = read('../Sources/State/DshState.swift')
const SETTINGS_SOURCE = read('../Sources/SettingsUI/SettingsViewModel.swift')
const PLUGIN_SOURCE = read('../Sources/Plugins/DshPluginManager.swift')
const PROJECT_SOURCE = read('../DSH.xcodeproj/project.pbxproj')
const HOST_PACKAGE = read('../assets/dsh-desktop-host/package.json')
const HOST_PATCH = read('../assets/dsh-desktop-host/cordis.patch.yml')
const HOST_WEB_SERVER = read('../assets/dsh-desktop-host/webserver.js')
const HOST_CONTROL = read('../assets/dsh-desktop-host/control.js')
const HOST_ROUTE = read('../assets/dsh-desktop-host/browser-url-route.js')
const LAN_ROUTE = read('../assets/dsh-desktop-host/lan-url-route.js')
const LAN_INGRESS = read('../assets/dsh-desktop-host/lan-http-ingress.js')
const BOOTSTRAP_SOURCE = read('../assets/dsh-runtime-bootstrap.mjs')
const NODE_RUNTIME_SOURCE = read('../Sources/Service/NodeRuntime.swift')

test('managed DSH receives access only through an inherited control pipe', () => {
  assert.match(SERVICE_SOURCE, /standardInput\s*=\s*access\.controlReadHandle/)
  assert.match(SERVICE_SOURCE, /DSH_DESKTOP_LAUNCH"\]\s*=\s*"1"/)
  assert.match(SERVICE_SOURCE, /DSH_DESKTOP_PORT"\]\s*=\s*String\(actualPort\)/)
  assert.match(SERVICE_SOURCE, /try\s+access\.sendBootstrap\(entryPath: entry, port: actualPort\)/)
  assert.match(SERVICE_SOURCE, /buildArguments\(runtimeBootstrap: runtimeBootstrap\)/)
  assert.match(SERVICE_SOURCE, /try\s+await\s+processIO\.waitForReady\(\)/)
  assert.match(SERVICE_SOURCE, /controlWriteHandle\.closeFile\(\)/)
  assert.doesNotMatch(SERVICE_SOURCE, /rendererToken.*environment|environment.*rendererToken/)
  assert.doesNotMatch(SERVICE_SOURCE, /rendererToken.*argument|argument.*rendererToken/)
})

test('generation credentials and NDJSON protocol are validated before encoding', () => {
  assert.match(ACCESS_SOURCE, /SecRandomCopyBytes/)
  assert.match(ACCESS_SOURCE, /replacingOccurrences\(of: "\+", with: "-"\)/)
  assert.match(ACCESS_SOURCE, /replacingOccurrences\(of: "\/", with: "_"\)/)
  assert.match(PROTOCOL_SOURCE, /maxLineBytes\s*=\s*16\s*\*\s*1024/)
  assert.match(PROTOCOL_SOURCE, /outputFormatting\s*=\s*\[\.sortedKeys\]/)
  assert.match(PROTOCOL_SOURCE, /Data\(\[0x0A\]\)/)
  assert.match(HOST_CONTROL, /MAX_LINE_BYTES\s*=\s*16\s*\*\s*1024/)
  assert.match(HOST_CONTROL, /JSON\.parse/)
  assert.match(HOST_CONTROL, /process\.exit\(1\)/)
  assert.match(HOST_CONTROL, /accessState\.applyPolicy/)
  assert.match(HOST_CONTROL, /shutdownControlledAccess/)
  assert.match(HOST_CONTROL, /control stream closed/)
  assert.match(HOST_CONTROL, /validateBootstrap/)
  assert.match(HOST_CONTROL, /waitForDesktopBootstrap/)
  assert.match(BOOTSTRAP_SOURCE, /process\.title = "DSH Web Runtime"/)
  assert.match(BOOTSTRAP_SOURCE, /await import\(bootstrap\.entryPath\)/)
  assert.match(STATE_SOURCE, /browserAccessEnabled/)
  assert.match(STATE_SOURCE, /networkExposure/)
  assert.match(STATE_SOURCE, /decodeIfPresent\(Bool\.self, forKey: \.browserAccessEnabled\) \?\? false/)
})

test('a managed control-pipe EOF exits before generation instead of leaving Node alive', async () => {
  const controlModule = new URL('../assets/dsh-desktop-host/control.js', import.meta.url).href
  const script = `import { startDesktopControl } from ${JSON.stringify(controlModule)}; startDesktopControl();`
  const child = spawn(process.execPath, ['--input-type=module', '--eval', script], {
    env: { ...process.env, DSH_DESKTOP_LAUNCH: '1' },
    stdio: ['pipe', 'ignore', 'pipe'],
  })
  let stderr = ''
  child.stderr.setEncoding('utf8')
  child.stderr.on('data', (chunk) => { stderr += chunk })
  child.stdin.end()

  const result = await new Promise((resolve, reject) => {
    child.once('error', reject)
    child.once('exit', (code, signal) => resolve({ code, signal }))
  })
  assert.equal(result.code, 1)
  assert.equal(result.signal, null)
  assert.match(stderr, /control stream closed before generation/)
})

test('browser access updates the live policy and opens only a short-lived Host URL', () => {
  assert.match(SETTINGS_SOURCE, /setBrowserAccessEnabled\(_ enabled: Bool\)/)
  assert.match(SETTINGS_SOURCE, /DshService\.shared\.setBrowserAccessEnabled/)
  assert.match(SETTINGS_SOURCE, /NSWorkspace\.shared\.open\(url\)/)
  assert.match(WINDOW_SOURCE, /URLSessionConfiguration\.ephemeral/)
  assert.match(WINDOW_SOURCE, /dsh_swift_renderer=\\\(session\.access\.rendererToken\)/)
  assert.match(WINDOW_SOURCE, /fetchAuthenticatedBrowserURL/)
  assert.match(HOST_ROUTE, /__dsh_swift\/browser-url/)
  assert.match(HOST_ROUTE, /CLASSIFICATIONS\.renderer/)
  assert.match(HOST_ROUTE, /connection\.authenticatedUrl/)
  assert.match(HOST_ROUTE, /cache-control.*no-store/i)
})

test('LAN access uses a separate authenticated HTTP ingress while the DSH server stays loopback-only', () => {
  assert.match(SERVICE_SOURCE, /setNetworkExposure\(_ exposure: DshNetworkExposure\)/)
  assert.match(SERVICE_SOURCE, /networkExposure: state\.networkExposure/)
  assert.match(PROCESS_IO_SOURCE, /loopback\|lan/)
  assert.match(WINDOW_SOURCE, /fetchLANURL/)
  assert.match(SETTINGS_SOURCE, /setNetworkExposure\(_ enabled: Bool\)/)
  assert.match(SETTINGS_SOURCE, /copyLANURL/)
  assert.match(LAN_ROUTE, /__dsh_swift\/lan-url/)
  assert.match(LAN_ROUTE, /CLASSIFICATIONS\.renderer/)
  assert.match(LAN_ROUTE, /networkExposure !== NETWORK_EXPOSURES\.lan/)
  assert.match(LAN_INGRESS, /listenHost = "0\.0\.0\.0"/)
  assert.match(LAN_INGRESS, /hasValidLanCredential/)
  assert.match(LAN_INGRESS, /RENDERER_COOKIE_NAME/)
  assert.match(LAN_INGRESS, /backendHeaders/)
  assert.match(HOST_WEB_SERVER, /createLanHTTPIngress/)
  assert.match(HOST_PACKAGE, /lan-url-route/)
  assert.match(HOST_PACKAGE, /lan-http-ingress/)
})

test('readiness requires both the loopback URL and the matching control generation', () => {
  assert.match(PROCESS_IO_SOURCE, /controlReadyGeneration\s*==\s*expectedGeneration/)
  assert.match(PROCESS_IO_SOURCE, /dsh desktop control ready/)
  assert.match(PROCESS_IO_SOURCE, /readabilityHandler/)
  assert.match(PROCESS_IO_SOURCE, /maxLogBytes\s*=\s*256\s*\*\s*1024/)
  assert.match(PROCESS_IO_SOURCE, /redact/)
  assert.match(PROCESS_IO_SOURCE, /DshProcessIOError\.generationMismatch/)
})

test('WebKit receives a strict, HttpOnly, session-only host cookie for each generation', () => {
  assert.match(COOKIE_SOURCE, /dsh_swift_renderer/)
  assert.match(COOKIE_SOURCE, /isHTTPOnly/)
  assert.match(COOKIE_SOURCE, /sameSiteStrict/)
  assert.match(COOKIE_SOURCE, /discard/)
  assert.match(COOKIE_SOURCE, /for cookie in oldCookies where/)
  assert.match(WINDOW_SOURCE, /bootstrapWebProfileManifestIfMissing\(\)/)
  assert.match(WINDOW_SOURCE, /ensureDesktopHostPlugin\(\)/)
  assert.match(WINDOW_SOURCE, /try\s+await\s+rendererCookieStore\.install\(for: session\)/)
  assert.match(WINDOW_SOURCE, /webView\?\.\s*load\(URLRequest\(url: session\.url\)\)/)
})

test('first launch bootstraps the canonical profile and installs the host before DSH starts', () => {
  assert.match(PLUGIN_SOURCE, /bootstrapWebProfileManifestIfMissing/)
  assert.match(PLUGIN_SOURCE, /"name": "dsh-profile-web"/)
  assert.match(PLUGIN_SOURCE, /dsh\.profile\.bundles/)
  assert.match(PLUGIN_SOURCE, /proc\.arguments = \[[\s\S]*"add"[\s\S]*file:/)
  assert.match(PLUGIN_SOURCE, /@deepseek-ai\/dsh-host-webserver@/)
  assert.match(PLUGIN_SOURCE, /validateDesktopHostBundle/)
  assert.match(PLUGIN_SOURCE, /isInstalledDesktopHostBundle/)
  assert.match(PLUGIN_SOURCE, /CryptoKit/)
  assert.match(PLUGIN_SOURCE, /SHA256/)
  assert.match(PLUGIN_SOURCE, /desktopHostBundleFingerprint/)
  assert.match(PLUGIN_SOURCE, /--force/)
  assert.match(PLUGIN_SOURCE, /removeInstalledDesktopHostBundle/)
  assert.match(PLUGIN_SOURCE, /isInstalledWebServerPackage/)
})

test('the upstream webserver is replaced and all request boundaries share the fence', () => {
  assert.match(HOST_PATCH, /id: webserver[\s\S]*disabled: true/)
  assert.match(HOST_PATCH, /name: dsh-desktop-host\/webserver/)
  assert.match(HOST_PATCH, /host: 127\.0\.0\.1/)
  assert.match(HOST_WEB_SERVER, /register\(route\)/)
  assert.match(HOST_WEB_SERVER, /registerFallback\(handler\)/)
  assert.match(HOST_WEB_SERVER, /registerUpgrade\(route\)/)
  assert.match(HOST_WEB_SERVER, /REQUIRED_UPSTREAM_METHODS/)
  assert.match(HOST_WEB_SERVER, /incompatible with the installed DSH runtime/)
  assert.match(HOST_WEB_SERVER, /requestPassesLoopbackFence/)
  assert.match(HOST_WEB_SERVER, /rejectUpgrade/)
  assert.match(HOST_WEB_SERVER, /accessState\.trackOrdinarySocket/)
  assert.match(HOST_WEB_SERVER, /createBrowserURLRoute/)
  assert.match(HOST_WEB_SERVER, /dsh_browser_auth=.*Max-Age=600/)
  assert.match(HOST_WEB_SERVER, /referrer-policy/i)
  assert.match(HOST_PACKAGE, /browser-url-route/)
  assert.match(HOST_PACKAGE, /"\.\/webserver": "\.\/webserver\.js"/)
  assert.match(HOST_PACKAGE, /"@deepseek-ai\/dsh-host-webserver"/)
  assert.match(PROJECT_SOURCE, /Security\.framework/)
  assert.match(PROJECT_SOURCE, /dsh-runtime-bootstrap\.mjs/)
  assert.match(NODE_RUNTIME_SOURCE, /resolveRuntimeBootstrap/)
})
