import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const read = (path) => fs.readFileSync(new URL(path, import.meta.url), 'utf8')
const STATE_SOURCE = read('../Sources/State/DshState.swift')
const SEMVER_SOURCE = read('../Sources/Versions/DshSemanticVersion.swift')
const VERSION_MANAGER_SOURCE = read('../Sources/Versions/DshVersionManager.swift')
const SETTINGS_SOURCE = read('../Sources/SettingsUI/SettingsViewModel.swift')
const SETTINGS_VIEW_SOURCE = read('../Sources/SettingsUI/SettingsView.swift')
const VERSIONS_VIEW_SOURCE = read('../Sources/SettingsUI/VersionsTabView.swift')
const GENERAL_SOURCE = read('../Sources/SettingsUI/GeneralTabView.swift')
const PLUGIN_SOURCE = read('../Sources/Plugins/DshPluginManager.swift')
const WINDOW_SOURCE = read('../Sources/MainWindow/MainWindowController.swift')
const SERVICE_SOURCE = read('../Sources/Service/DshService.swift')
const HOST_CONTROL = read('../assets/dsh-desktop-host/control.js')
const APP_SOURCE = read('../Sources/AppDelegate.swift')

test('runtime state persists active, previous, pending, and transaction phase', () => {
  assert.match(STATE_SOURCE, /public struct NpmRuntimeDescriptor: Codable, Equatable, Sendable/)
  assert.match(STATE_SOURCE, /public struct DshRuntimeState: Codable, Equatable, Sendable/)
  assert.match(STATE_SOURCE, /case alpha/)
  assert.match(STATE_SOURCE, /var active: NpmRuntimeDescriptor\?/)
  assert.match(STATE_SOURCE, /var previous: NpmRuntimeDescriptor\?/)
  assert.match(STATE_SOURCE, /var pending: NpmRuntimeDescriptor\?/)
  assert.match(STATE_SOURCE, /public var phase: DshRuntimeTransactionPhase/)
  assert.match(STATE_SOURCE, /public var webProfileSnapshotID: String\?/)
  assert.match(STATE_SOURCE, /public var dismissedAppVersion: String\?/)
  assert.match(STATE_SOURCE, /public var healthyStartCount: Int/)
  assert.match(STATE_SOURCE, /public var lastDiagnostic: String\?/)
  assert.match(STATE_SOURCE, /decodeIfPresent\(DshRuntimeState\.self, forKey: \.runtimeState\)/)
})

test('the app defaults to an isolated desktop Profile and exposes web as an explicit option', () => {
  assert.match(STATE_SOURCE, /public enum DshAppProfile:.*CaseIterable/)
  assert.match(STATE_SOURCE, /case desktop/)
  assert.match(STATE_SOURCE, /case web/)
  assert.match(STATE_SOURCE, /appProfile: DshAppProfile = \.desktop/)
  assert.match(STATE_SOURCE, /decodeIfPresent\(DshAppProfile\.self, forKey: \.appProfile\) \?\? \.desktop/)
  assert.match(SETTINGS_SOURCE, /public var appProfile: DshAppProfile/)
  assert.match(SETTINGS_SOURCE, /public func setAppProfile\(_ profile: DshAppProfile\)/)
  assert.match(SETTINGS_SOURCE, /appProfile == \.desktop/)
  assert.match(SETTINGS_SOURCE, /暂不允许升级 DSH Runtime/)
  assert.match(SETTINGS_SOURCE, /previous\.rawValue/)
  assert.match(GENERAL_SOURCE, /DSH Profile/)
  assert.match(GENERAL_SOURCE, /DshAppProfile\.allCases/)
  assert.match(GENERAL_SOURCE, /pickerStyle\(\.menu\)/)
  assert.match(GENERAL_SOURCE, /终端 dsh web 共享插件和依赖/)
  assert.match(VERSIONS_VIEW_SOURCE, /runtimeUpdatesAllowed/)
  assert.match(VERSIONS_VIEW_SOURCE, /web Profile 已禁用 Runtime 更新/)
  assert.match(VERSIONS_VIEW_SOURCE, /disabled\(!runtimeUpdatesAllowed\)/)
  assert.match(PLUGIN_SOURCE, /profileDirectory\(for profile: DshAppProfile\)/)
  assert.match(PLUGIN_SOURCE, /public func removeDesktopHostArtifacts\(from profile: DshAppProfile\)/)
  assert.match(PLUGIN_SOURCE, /guard profile == \.web else/)
  assert.match(PLUGIN_SOURCE, /proc\.arguments = \["remove"\] \+ dependenciesToRemove/)
  assert.match(PLUGIN_SOURCE, /--config\.minimum-release-age=0/)
  assert.match(PLUGIN_SOURCE, /dsh-host-webserver/)
  assert.match(SERVICE_SOURCE, /profile: state\.appProfile/)
  assert.match(HOST_CONTROL, /SUPPORTED_PROFILES = new Set\(\["desktop", "web"\]\)/)
})

test('runtime state migration prepares descriptors before taking the state lock', () => {
  assert.doesNotMatch(VERSION_MANAGER_SOURCE, /state\.runtimeState\.active\s*=\s*runtimeDescriptor\(/)
  assert.match(VERSION_MANAGER_SOURCE, /let descriptor = runtimeDescriptor\(version: first\)[\s\S]{0,180}DshStateManager\.shared\.update/)
})

test('npm runtime updates use SemVer ordering and a staging candidate', () => {
  assert.match(SEMVER_SOURCE, /public let prerelease: \[String\]/)
  assert.match(SEMVER_SOURCE, /public let buildMetadata: \[String\]/)
  assert.match(SEMVER_SOURCE, /if leftNumeric != rightNumeric/)
  assert.match(VERSION_MANAGER_SOURCE, /public func installCandidate\(/)
  assert.match(VERSION_MANAGER_SOURCE, /\["alpha", "rc"\]/)
  assert.match(VERSION_MANAGER_SOURCE, /public func discardInstalledVersion\(/)
  assert.match(VERSION_MANAGER_SOURCE, /public func cleanupUnreferencedVersions\(\)/)
  assert.match(VERSION_MANAGER_SOURCE, /let alignedFamily = try await resolveAlignedFamily\(version: version, registry: reg\)/)
  assert.match(VERSION_MANAGER_SOURCE, /activateWhenMissing: Bool = true/)
  assert.match(VERSION_MANAGER_SOURCE, /private func verifyNpmIntegrity\(/)
  assert.match(VERSION_MANAGER_SOURCE, /expectedIntegrity: String/)
  assert.doesNotMatch(VERSION_MANAGER_SOURCE, /public func uninstallVersion\(/)
  assert.match(STATE_SOURCE, /public static func begin\(/)
  assert.match(STATE_SOURCE, /phase: \.staging/)
  assert.match(STATE_SOURCE, /public static func beginVerification\(/)
  assert.match(STATE_SOURCE, /next\.phase = \.verifying/)
  assert.match(STATE_SOURCE, /public static func beginRollback\(/)
  assert.match(STATE_SOURCE, /next\.phase = \.rollingBack/)
  assert.match(SETTINGS_SOURCE, /DshRuntimeTransaction\.begin\(/)
  assert.match(SETTINGS_SOURCE, /DshRuntimeTransaction\.beginVerification\(/)
  assert.match(SETTINGS_SOURCE, /DshRuntimeTransaction\.beginRollback\(/)
  assert.match(SETTINGS_SOURCE, /DshRuntimeTransaction\.recordRollbackFailure\(/)
  assert.match(SETTINGS_SOURCE, /dismissedVersion = item\.version/)
  assert.match(SETTINGS_SOURCE, /dismissedAppVersion = currentAppVersion/)
  assert.match(SETTINGS_SOURCE, /dismissedVersion == latest/)
  assert.match(SETTINGS_SOURCE, /actually passes the normal startup health gate/)
  assert.match(SETTINGS_SOURCE, /withRuntimeOperation/)
  assert.match(SETTINGS_SOURCE, /recoverPendingRuntimeUpdate\(\) async/)
  assert.match(SETTINGS_SOURCE, /public func recordHealthyRuntimeStart\(\) async/)
  assert.match(SETTINGS_SOURCE, /已自动恢复/)
})

test('runtime family installation fails closed and keeps npm registry metadata', () => {
  assert.match(VERSION_MANAGER_SOURCE, /guard alignedFamily\.missing\.isEmpty else/)
  assert.match(VERSION_MANAGER_SOURCE, /integrity: dist\?\["integrity"\] as\? String/)
  assert.match(VERSION_MANAGER_SOURCE, /public static func normalizedRegistry\(/)
  assert.match(PLUGIN_SOURCE, /private func registryArguments\(\)/)
  assert.match(PLUGIN_SOURCE, /registryArguments\(\)/)
  assert.match(PLUGIN_SOURCE, /public func createWebProfileSnapshot\([\s\S]*\) async throws -> String/)
  assert.match(PLUGIN_SOURCE, /public func restoreWebProfileSnapshot\([\s\S]*_ id: String,[\s\S]*\) async throws/)
  assert.match(PLUGIN_SOURCE, /public func deleteWebProfileSnapshot\(_ id: String\) async throws/)
  assert.match(PLUGIN_SOURCE, /Task\.detached\(priority: \.utility\)/)
  assert.match(PLUGIN_SOURCE, /cloneDirectoryIfPossible/)
  assert.match(PLUGIN_SOURCE, /attemptedClone/)
  assert.match(PLUGIN_SOURCE, /removeItem\(at: destination\)/)
  assert.match(PLUGIN_SOURCE, /volumeAvailableCapacityForImportantUsage/)
  assert.match(PLUGIN_SOURCE, /DshProfileSnapshotProgress/)
})

test('version settings expose only one-way npm latest updates', () => {
  assert.match(VERSIONS_VIEW_SOURCE, /更新到/)
  assert.match(VERSIONS_VIEW_SOURCE, /viewModel\.updateToSelectedChannel\(\)/)
  assert.match(VERSIONS_VIEW_SOURCE, /DshRuntimeChannel\.next/)
  assert.match(VERSIONS_VIEW_SOURCE, /DshRuntimeChannel\.alpha/)
  assert.match(VERSIONS_VIEW_SOURCE, /pickerStyle\(\.menu\)/)
  assert.doesNotMatch(VERSIONS_VIEW_SOURCE, /selectVersion\(/)
  assert.doesNotMatch(VERSIONS_VIEW_SOURCE, /uninstallVersion\(/)
  assert.doesNotMatch(VERSIONS_VIEW_SOURCE, /安装此版本/)
})

test('the running Runtime channel is independent from the update-channel picker', () => {
  assert.match(STATE_SOURCE, /public static func inferred\(from version: String\) -> DshRuntimeChannel/)
  assert.match(STATE_SOURCE, /case "alpha":\s*return \.alpha/)
  assert.match(STATE_SOURCE, /case "rc":\s*return \.next/)
  assert.match(VERSIONS_VIEW_SOURCE, /private var activeChannelName: String/)
  assert.match(VERSIONS_VIEW_SOURCE, /DshRuntimeChannel\.inferred\(from: currentVersion\)/)

  const runtimeCard = VERSIONS_VIEW_SOURCE.slice(
    VERSIONS_VIEW_SOURCE.indexOf('"DSH Runtime"'),
    VERSIONS_VIEW_SOURCE.indexOf('if viewModel.isInstallingVersion')
  )
  assert.match(runtimeCard, /activeChannelName/)
  assert.doesNotMatch(runtimeCard, /channelName/)
})

test('plugin install asks before bypassing the minimum release age policy', () => {
  assert.match(PLUGIN_SOURCE, /public func addPlugin\(spec: String, ignoringMinimumReleaseAge: Bool = false\)/)
  assert.match(PLUGIN_SOURCE, /MINIMUM_RELEASE_AGE_VIOLATION/)
  assert.match(PLUGIN_SOURCE, /if ignoringMinimumReleaseAge[\s\S]*--config\.minimum-release-age=0/)
  assert.match(PLUGIN_SOURCE, /let stdout = Pipe\(\)[\s\S]*let stderr = Pipe\(\)[\s\S]*processOutput\(result\)/)
  assert.match(SETTINGS_SOURCE, /pendingPluginInstallSpec/)
  assert.match(SETTINGS_SOURCE, /confirmPendingPluginInstall\(\)/)
  assert.match(SETTINGS_SOURCE, /isMinimumReleaseAgeViolation\(error\)/)
  assert.match(SETTINGS_VIEW_SOURCE, /confirmationDialog\(/)
  assert.match(SETTINGS_VIEW_SOURCE, /继续安装插件？/)
  assert.match(SETTINGS_SOURCE, /不会修改全局 pnpm 配置/)
})

test('runtime confirmation waits for the rendered Web UI after navigation', () => {
  assert.match(WINDOW_SOURCE, /try await (?:self\.)?waitForWebUIReady\(\)/)
  assert.match(WINDOW_SOURCE, /try await verifyRuntimeHealth\(session: authenticatedSession, upstreamCookies: upstreamCookies\)/)
  assert.match(WINDOW_SOURCE, /匿名 loopback/)
  assert.match(WINDOW_SOURCE, /verifyBrowserAccessBoundary/)
  assert.match(WINDOW_SOURCE, /verifyLANAccessBoundary/)
  assert.match(SERVICE_SOURCE, /final class DshAsyncOperationGate/)
  assert.match(SERVICE_SOURCE, /startOperationGate\.acquire\(\)/)
  assert.match(WINDOW_SOURCE, /DshAsyncOperationGate/)
  assert.match(WINDOW_SOURCE, /restartDshServiceDuringOperation/)
  assert.match(WINDOW_SOURCE, /createWebProfileSnapshot/)
  assert.match(WINDOW_SOURCE, /await DshService\.shared\.stopAndWait\(\)/)
  assert.match(WINDOW_SOURCE, /restoreWebProfileSnapshot\(snapshotID, profile: appProfile\) \{ progress in/)
  assert.match(WINDOW_SOURCE, /private func beginWebUIReadinessCheck\(/)
  assert.match(WINDOW_SOURCE, /pendingWebUINavigation/)
  assert.match(WINDOW_SOURCE, /completeWebUIReadiness\(\.success\(\(\)\)\)/)
  assert.match(WINDOW_SOURCE, /webView\(_ webView: WKWebView, didFinish navigation:/)
})

test('runtime update policy defaults to notify and labels failure stages', () => {
  assert.match(STATE_SOURCE, /updatePolicy: DshRuntimeUpdatePolicy = \.notify/)
  assert.match(STATE_SOURCE, /autoFollowLatest: Bool = false/)
  assert.match(STATE_SOURCE, /self\.autoFollowLatest = runtimeState\.updatePolicy == \.automaticStable/)
  assert.match(STATE_SOURCE, /self\.updatePolicy = \.notify/)
  assert.match(SETTINGS_SOURCE, /DshRuntimeUpdateFailure/)
  assert.match(SETTINGS_SOURCE, /candidate Runtime/)
  assert.match(SETTINGS_SOURCE, /启动或健康检查失败/)
  assert.match(SETTINGS_SOURCE, /public var runtimeChannel: DshRuntimeChannel/)
  assert.match(SETTINGS_SOURCE, /public var alphaVersion: String\?/)
  assert.match(SETTINGS_SOURCE, /public func updateToSelectedChannel\(\)/)
  assert.match(SETTINGS_SOURCE, /state\.runtimeState\.channel = runtimeChannel/)
  assert.match(SETTINGS_SOURCE, /catalogRequestGeneration/)
  assert.match(SETTINGS_SOURCE, /availableVersions = \[\]/)
  assert.doesNotMatch(GENERAL_SOURCE, /更新通道：next/)
  assert.doesNotMatch(GENERAL_SOURCE, /自动更新已开启/)
  assert.match(VERSIONS_VIEW_SOURCE, /自动更新已开启/)
  assert.match(VERSIONS_VIEW_SOURCE, /automaticUpdatesAllowed/)
  assert.match(VERSIONS_VIEW_SOURCE, /切回 stable（latest）后才可以重新启用/)
  assert.match(VERSIONS_VIEW_SOURCE, /disabled\(!automaticUpdatesAllowed\)/)
  assert.match(SETTINGS_SOURCE, /runtimeChannel != \.latest[\s\S]*autoFollowLatest/)
  assert.match(VERSIONS_VIEW_SOURCE, /channelDescription/)
  assert.match(VERSIONS_VIEW_SOURCE, /runtimeChannelSelection/)
})

test('startup recovery restores a Profile at most once and retries retained cleanup', () => {
  assert.match(APP_SOURCE, /await SettingsViewModel\.shared\.recoverPendingRuntimeUpdate\(\)/)
  assert.match(APP_SOURCE, /await SettingsViewModel\.shared\.retryRetainedWebProfileSnapshotCleanup\(\)/)
  assert.ok(APP_SOURCE.indexOf('recoverPendingRuntimeUpdate') < APP_SOURCE.indexOf('MainWindowController.shared.launch'))
  assert.match(SETTINGS_SOURCE, /public func retryRetainedWebProfileSnapshotCleanup\(\) async/)
  assert.match(WINDOW_SOURCE, /try await withRuntimeOperation \{[\s\S]*await SettingsViewModel\.shared\.recordHealthyRuntimeStart\(\)/)
  const rollbackRecovery = SETTINGS_SOURCE.slice(
    SETTINGS_SOURCE.indexOf('case .rollback'),
    SETTINGS_SOURCE.indexOf('case .reset')
  )
  assert.doesNotMatch(rollbackRecovery, /restoreWebProfileSnapshot/)
})

test('healthy-start cleanup validates the persisted count before committing', () => {
  const cleanup = SETTINGS_SOURCE.slice(
    SETTINGS_SOURCE.indexOf('public func recordHealthyRuntimeStart()'),
    SETTINGS_SOURCE.indexOf('/// Retry a snapshot deletion')
  )
  assert.ok(
    (cleanup.match(/healthyStartCount == nextCount - 1/g) || []).length >= 2,
    'post-cleanup and commit guards must compare against the persisted pre-commit count'
  )
  assert.match(cleanup, /healthyStartCount = 0[\s\S]*phase = \.idle/)
})
